CREATE DATABASE DA1_QuanLyBanGiay
GO
USE DA1_QuanLyBanGiay
GO

-- ChucVu
CREATE TABLE ChucVu(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(50) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL
)
GO

-- KichCo
CREATE TABLE KichCo(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
CoGiay VARCHAR(20) UNIQUE
)
GO

-- DeGiay
CREATE TABLE DeGiay(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
ChatLieu NVARCHAR(50) DEFAULT NULL
)
GO

-- DongSP
CREATE TABLE DongSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(50) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL
)
GO

-- Color SanPham
CREATE TABLE MauSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Mau NVARCHAR(50) DEFAULT NULL
)
GO

-- Nha SX
CREATE TABLE NhaSX(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() ,
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL,
DiaChi NVARCHAR(50) DEFAULT NULL
)
GO

-- TaiKhoan
CREATE TABLE TaiKhoan(
Username NVARCHAR(50) NOT NULL Primary Key,
Password NVARCHAR(50) NOT NULL,
IdNV UNIQUEIDENTIFIER,
TrangThai BIT
)
GO

-- KhuyenMai
CREATE TABLE Vouncher(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(50) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL,
GiamGia FLOAT,
NgayBatDau DATE DEFAULT NULL,
NgayHetHan DATE DEFAULT NULL,
GhiChu NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 0
)
GO

-- KhachHang
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(50) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(50) DEFAULT NULL,
)
GO

-- NhanVien
CREATE TABLE NhanVien(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdCV UNIQUEIDENTIFIER,
Ma VARCHAR(50) UNIQUE,
Ten NVARCHAR(50),
SDT VARCHAR(30) DEFAULT NULL,
Email  VARCHAR(100) DEFAULT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL
)
GO

CREATE TABLE LichLamViec(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdNV UNIQUEIDENTIFIER,
IdCaLam UNIQUEIDENTIFIER
)

CREATE TABLE CaLam(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenCa NVARCHAR(50)
)

-- ChiTietSP
CREATE TABLE ChiTietSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdSP UNIQUEIDENTIFIER,
IdMauSP UNIQUEIDENTIFIER,
IdKichCo UNIQUEIDENTIFIER,
SoLuong INT
)
GO

-- SanPham
CREATE TABLE SanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdDongSP UNIQUEIDENTIFIER,
IdDeGiay UNIQUEIDENTIFIER,
IdNSX UNIQUEIDENTIFIER,
NgayNhapHang DATE DEFAULT NULL,
GiaNhap DECIMAL(20,0) DEFAULT 0,
GiaBan DECIMAL(20,0) DEFAULT 0,
XuatXu NVARCHAR(50) DEFAULT NULL,
TrangThai int DEFAULT 0
)
GO

-- HoaDon
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
IdVoucher UNIQUEIDENTIFIER,
Ma VARCHAR(50) UNIQUE,
NgayTao DATE DEFAULT NULL,
NgayThanhToan DATE DEFAULT NULL,
TongTien DECIMAL(20,0) DEFAULT 0,
GhiChu nvarchar(MAX),
TrangThai INT DEFAULT 0
)
GO
-- HoaDonCT
CREATE TABLE HoaDonCT(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHoaDon UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0
)
GO
-- GioHang
CREATE TABLE GioHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
Ma VARCHAR(50) UNIQUE,
NgayTao DATE DEFAULT NULL,
NgayThanhToan DATE DEFAULT NULL,
Ten NVARCHAR(50) DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
DiaChi NVARCHAR(50) DEFAULT NULL,
TinhTrang INT DEFAULT 0
)
Go

-- GioHangCT
CREATE TABLE GioHangCT(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdGioHang UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0
)

--TAO QUAN HE GIUA CÁC BANG
-- GioHang
ALTER TABLE GioHang ADD FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
ALTER TABLE GioHang ADD FOREIGN KEY (IdNV) REFERENCES NhanVien(Id)

-- GioHangCT
ALTER TABLE GioHangCT ADD FOREIGN KEY (IdGioHang) REFERENCES GioHang(Id)
ALTER TABLE GioHangCT ADD FOREIGN KEY (IdChiTietSP) REFERENCES ChiTietSP(Id)

--NhanVien - ChucVu
ALTER TABLE NhanVien ADD FOREIGN KEY (IdCV) REFERENCES ChucVu(Id)

-- SanPham - CTSanPham
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdSP) REFERENCES SanPham(Id)
ALTER TABLE SanPham ADD FOREIGN KEY(IdDongSP) REFERENCES DongSP(Id)
ALTER TABLE SanPham ADD FOREIGN KEY(IdDeGiay) REFERENCES DeGiay(Id)
ALTER TABLE SanPham ADD FOREIGN KEY(IdNSX) REFERENCES NhaSX(Id)

-- ChiTietSP
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdMauSP) REFERENCES MauSP(Id)
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdKichCo) REFERENCES KichCo(Id)

-- CaLam -- Nhan Vien -- LichLamViec
ALTER TABLE LichLamViec ADD FOREIGN KEY(IdNV) REFERENCES NhanVien(Id)
ALTER TABLE LichLamViec ADD FOREIGN KEY(IdCaLam) REFERENCES CaLam(Id)


--TaiKhoan - NhanVien
ALTER TABLE TaiKhoan ADD FOREIGN KEY(IdNV) REFERENCES NhanVien(Id)

--HoaDonCT
ALTER TABLE HoaDonCT ADD FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id)
ALTER TABLE HoaDonCT ADD FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id)
-- HoaDon - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
-- HoaDon - NhanVien
ALTER TABLE HoaDon ADD FOREIGN KEY (IdNV) REFERENCES NhanVien(Id)
-- HoaDon - Voucher
ALTER TABLE HoaDon ADD FOREIGN KEY (IdVoucher) REFERENCES Vouncher(Id)



INSERT INTO KichCo (CoGiay) VALUES ('36');
INSERT INTO KichCo (CoGiay) VALUES ('37');
INSERT INTO KichCo (CoGiay) VALUES ('38');

INSERT INTO DeGiay (ChatLieu) VALUES (N'Da bò');
INSERT INTO DeGiay (ChatLieu) VALUES (N'Da cá sấu');
INSERT INTO DeGiay (ChatLieu) VALUES (N'Da lộn');

INSERT INTO DongSP (Ma, Ten) VALUES ('DS001', N'Giày thể thao');
INSERT INTO DongSP (Ma, Ten) VALUES ('DS002', N'Giày cao gót');
INSERT INTO DongSP (Ma, Ten) VALUES ('DS003', N'Giày búp bê');

INSERT INTO MauSP (Ma, Mau) VALUES ('M001', N'Đen');
INSERT INTO MauSP (Ma, Mau) VALUES ('M002', N'Trắng');
INSERT INTO MauSP (Ma, Mau) VALUES ('M003', N'Đỏ');

INSERT INTO NhaSX (Ma, Ten, DiaChi) VALUES ('NSX001', 'Nike', N'Mỹ');
INSERT INTO NhaSX (Ma, Ten, DiaChi) VALUES ('NSX002', 'Adidas', N'Đức');
INSERT INTO NhaSX (Ma, Ten, DiaChi) VALUES ('NSX003', 'Puma', N'Đức');

INSERT INTO KhachHang (Ma, Ten, SDT, NgaySinh, DiaChi) VALUES ('KH001', N'Nguyễn Văn A', '0901234567', '1990-01-01', N'Tp. Hồ Chí Minh');
INSERT INTO KhachHang (Ma, Ten, SDT, NgaySinh, DiaChi) VALUES ('KH002', N'Trần Thị B', '0987654321', '1995-05-05', N'Hà Nội');
INSERT INTO KhachHang (Ma, Ten, SDT, NgaySinh, DiaChi) VALUES ('KH003', N'Lê Văn C', '0912345678', '1992-02-02', N'Đà Nẵng');
INSERT INTO KhachHang (Ma, Ten, SDT, NgaySinh, DiaChi) VALUES ('KH004', N'Phạm Thị D', '0976543210', '1988-08-08', N'Thái Bình');
INSERT INTO KhachHang (Ma, Ten, SDT, NgaySinh, DiaChi) VALUES ('KH005', N'Nguyễn Văn E', '0923456789', '1999-09-09', N'Bình Dương');

INSERT INTO TaiKhoan (Username, Password, TrangThai) VALUES ('user1', 'pass1', 1);
INSERT INTO TaiKhoan (Username, Password, TrangThai) VALUES ('user2', 'pass2', 1);
INSERT INTO TaiKhoan (Username, Password, TrangThai) VALUES ('user3', 'pass3', 0);
INSERT INTO TaiKhoan (Username, Password, TrangThai) VALUES ('user4', 'pass4', 1);
INSERT INTO TaiKhoan (Username, Password, TrangThai) VALUES ('user5', 'pass5', 0);

INSERT INTO ChucVu (Ma, Ten) VALUES ('CV001', N'Quản lý');
INSERT INTO ChucVu (Ma, Ten) VALUES ('CV002', N'Nhân viên bán hàng');
INSERT INTO ChucVu (Ma, Ten) VALUES ('CV003', N'Nhân viên kho');

INSERT INTO CaLam (TenCa) VALUES (N'Ca sáng');
INSERT INTO CaLam (TenCa) VALUES (N'Ca chiều');
INSERT INTO CaLam (TenCa) VALUES (N'Ca tối');

INSERT INTO NhanVien ( Ma, Ten, SDT, Email, GioiTinh, NgaySinh, DiaChi) VALUES ( 'NV001', N'Nguyễn Văn A', '0901234567', 'nguyenvana@example.com', N'Nam', '1990-01-01', N'Tp. Hồ Chí Minh');
INSERT INTO NhanVien ( Ma, Ten, SDT, Email, GioiTinh, NgaySinh, DiaChi) VALUES ( 'NV002', N'Trần Thị B', '0987654321', 'tranthib@example.com', N'Nữ', '1995-05-05', N'Hà Nội');
INSERT INTO NhanVien ( Ma, Ten, SDT, Email, GioiTinh, NgaySinh, DiaChi) VALUES ( 'NV003', N'Lê Văn C', '0912345678', 'levanc@example.com', N'Nam', '1992-02-02', N'Đà Nẵng');
INSERT INTO NhanVien ( Ma, Ten, SDT, Email, GioiTinh, NgaySinh, DiaChi) VALUES ( 'NV004', N'Phạm Thị D', '0976543210', 'phamthid@example.com', N'Nữ', '1988-08-08', N'Thái Bình');
INSERT INTO NhanVien ( Ma, Ten, SDT, Email, GioiTinh, NgaySinh, DiaChi) VALUES ( 'NV005', N'Nguyễn Văn E', '0923456789', 'nguyenvane@example.com', N'Nam', '1999-09-09', N'Bình Dương');

INSERT INTO ChiTietSP ( SoLuong) VALUES ( 100);
INSERT INTO ChiTietSP ( SoLuong) VALUES ( 200);
INSERT INTO ChiTietSP ( SoLuong) VALUES ( 150);

INSERT INTO SanPham ( NgayNhapHang, GiaNhap, GiaBan, XuatXu ) VALUES ( '2022-01-01', 500000, 800000, N'Việt Nam');
INSERT INTO SanPham ( NgayNhapHang, GiaNhap, GiaBan, XuatXu ) VALUES ( '2022-02-01', 1000000, 1500000, N'Đức');
INSERT INTO SanPham ( NgayNhapHang, GiaNhap, GiaBan, XuatXu ) VALUES ( '2022-03-01', 800000, 1200000, N'Mỹ');

INSERT INTO HoaDon ( Ma, NgayTao, NgayThanhToan, TongTien) VALUES ('HD001', '2022-01-01', '2022-01-05', 800000);
INSERT INTO HoaDon ( Ma, NgayTao, NgayThanhToan, TongTien) VALUES ('HD002', '2022-02-01', '2022-02-05', 1350000);
INSERT INTO HoaDon ( Ma, NgayTao, NgayThanhToan, TongTien) VALUES ('HD003', '2022-03-01', '2022-03-05', 1200000);

INSERT INTO HoaDonCT ( SoLuong, DonGia) VALUES ( 1, 800000);
INSERT INTO HoaDonCT ( SoLuong, DonGia) VALUES ( 2, 750000);
INSERT INTO HoaDonCT ( SoLuong, DonGia) VALUES ( 3, 400000);


INSERT INTO Vouncher (Ma, Ten, GiamGia, NgayBatDau, NgayHetHan, GhiChu) VALUES ('VC001', N'Voucher giảm giá 10%', 10, '2022-01-01', '2022-03-31', N'Áp dụng cho đơn hàng từ 1.000.000 đồng trở lên');
INSERT INTO Vouncher (Ma, Ten, GiamGia, NgayBatDau, NgayHetHan, GhiChu) VALUES ('VC002', N'Voucher giảm giá 20%', 20, '2022-02-01', '2022-04-30', N'Áp dụng cho đơn hàng từ 2.000.000 đồng trở lên');

INSERT INTO GioHang ( Ma, NgayTao, NgayThanhToan, Ten, SDT, DiaChi) VALUES ( 'GH001', '2022-01-01', '2022-01-05', N'Giỏ hàng Nguyễn Văn A', '0123456789', N'Hà Nội');
INSERT INTO GioHang ( Ma, NgayTao, NgayThanhToan, Ten, SDT, DiaChi) VALUES ( 'GH002', '2022-02-01', '2022-02-05', N'Giỏ hàng Trần Thị B', '0987654321', N'Hồ Chí Minh');

INSERT INTO GioHangCT ( SoLuong, DonGia) VALUES ( 1, 800000);
INSERT INTO GioHangCT ( SoLuong, DonGia) VALUES ( 2, 750000);